### ISSUE TITLE
client.view返回"输入字符串的格式不正确"

### ISSUE THREAD

**Issue by luowenjian** [cashlifei/Kingdee-K3Cloud-Web-Api#2]
用client.view查了几张表都提示“输入字符串的格式不正确”
例如：
```
K3CloudApiClient client = new K3CloudApiClient(K3CloudURL);
Boolean result = client.login(dbId, uid, pwd, lang);
if (result) {
    String sResult = client.view("ORG_Organizations", "{\"CreateOrgId\":\"0\",\"Number\":\"\",\"Id\":\"\"}");
    System.out.println(sResult);
} else {
    System.out.println("loginFail:"+result);
}
```
**sResult:**

{"Result":{"ResponseStatus":{"ErrorCode":500,"IsSuccess":false,"Errors":[{"FieldName":"输入字符串的格式不正确。","Message":"   在 System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)\r\n   在 System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)\r\n   在 System.String.System.IConvertible.ToInt64(IFormatProvider provider)\r\n   在 Kingdee.BOS.WebApi.FormService.View.Execute()\r\n   在 Kingdee.BOS.WebApi.FormService.BillOperationService.ExecuteOperation(FormOperation op, String data)","DIndex":0}],"SuccessEntitys":[],"SuccessMessages":[],"MsgCode":0}}}

**Comment by cashlifei** [comment]
你要按k3cloud webapi接口中的操作JSON格式去请求，如有问题，请尽量提供你完整的webapi操作文本。view接口需要提供number或者ID，至少一个.
 k3CloudService.K3CloudApiView("ORG_Organizations", "{\"CreateOrgId\":\"0\",\"Number\":\"\",\"Id\":\"10038\"}");
` k3CloudService.K3CloudApiView("ORG_Organizations", "{\"CreateOrgId\":\"0\",\"Number\":\"\",\"Id\":\"10038\"}");`

**Comment by luowenjian** [comment]
找到原因了，因为不熟悉这套系统，以为查询列表就是用缺省查询的形式获取。正确的方法是executeBillQuery
